### ISSUE TITLE
RunsInThreadsTest fails with ClassCastException ~10% of the time

### ISSUE THREAD

**Issue by jsoroka** [llorllale/cactoos-matchers#22]
On Fedora26, Oracle JDK8 u171 x64.

Looks like `RunsInThreadTest` assumes that concurrent modification of a `HashMap` only generates `ConcurrentModificationException` but actually one must not assume any particular exception type when there is more than one thread accessing the HashMap.

```
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.536 sec <<< FAILURE! - in org.llorllale.cactoos.matchers.RunsInThreadsTest
matchNegative(org.llorllale.cactoos.matchers.RunsInThreadsTest)  Time elapsed: 0.21 sec  <<< ERROR!
java.io.UncheckedIOException: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
        at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:60)
        at org.llorllale.cactoos.matchers.RunsInThreads.matchesSafely(RunsInThreads.java:109)
        at org.llorllale.cactoos.matchers.RunsInThreadsTest.matchNegative(RunsInThreadsTest.java:65)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
        at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
        at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
        at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.IOException: java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
        at org.cactoos.func.UncheckedFunc.lambda$apply$0(UncheckedFunc.java:58)
        at org.cactoos.scalar.CheckedScalar.value(CheckedScalar.java:84)
        at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
        at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
        at org.cactoos.func.UncheckedFunc.apply(UncheckedFunc.java:59)
        at org.cactoos.scalar.CheckedScalar.wrappedException(CheckedScalar.java:108)
        at org.cactoos.scalar.CheckedScalar.value(CheckedScalar.java:93)
        at org.cactoos.scalar.IoCheckedScalar.value(IoCheckedScalar.java:65)
        at org.cactoos.scalar.UncheckedScalar.value(UncheckedScalar.java:58)
        ... 20 more
Caused by: java.util.concurrent.ExecutionException: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
        at java.util.concurrent.FutureTask.report(FutureTask.java:122)
        at java.util.concurrent.FutureTask.get(FutureTask.java:192)
        at org.cactoos.scalar.And.lambda$null$0(And.java:111)
        at org.cactoos.scalar.And.value(And.java:137)
        at org.cactoos.scalar.And.value(And.java:61)
        at org.cactoos.scalar.CheckedScalar.value(CheckedScalar.java:84)
        ... 22 more
Caused by: java.lang.ClassCastException: java.util.HashMap$Node cannot be cast to java.util.HashMap$TreeNode
        at java.util.HashMap$TreeNode.moveRootToFront(HashMap.java:1832)
        at java.util.HashMap$TreeNode.putTreeVal(HashMap.java:2012)
        at java.util.HashMap.putVal(HashMap.java:638)
        at java.util.HashMap.put(HashMap.java:612)
        at org.llorllale.cactoos.matchers.RunsInThreadsTest.modify(RunsInThreadsTest.java:88)
        at org.llorllale.cactoos.matchers.RunsInThreads.lambda$matchesSafely$0(RunsInThreads.java:98)
        ... 4 more
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by dgroup** [comment]
https://travis-ci.org/llorllale/cactoos-matchers/builds/457480519?utm_source=github_status&utm_medium=notification
Oracle JDK8 (java-8-oracle)
```java
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.168 sec <<< FAILURE! - in org.llorllale.cactoos.matchers.RunsInThreadsTest
matchNegative(org.llorllale.cactoos.matchers.RunsInThreadsTest)  Time elapsed: 0.167 sec  <<< FAILURE!
java.lang.AssertionError: 
Can concurrently modify HashMap
Expected: <false>
     but: was <true>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.llorllale.cactoos.matchers.RunsInThreadsTest.matchNegative(RunsInThreadsTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

**Comment by llorllale** [comment]
@0crat in

**Comment by 0crat** [comment]
> @0crat in ([here](https://github.com/llorllale/cactoos-matchers/issues/22#issuecomment-442660871))

@llorllale Job [#22](https://github.com/llorllale/cactoos-matchers/issues/22) is now in scope, role is `DEV`

**Comment by 0crat** [comment]
Bug was reported, see [§29](http://www.zerocracy.com/policy.html#29): +15 point(s) just awarded to @jsoroka[/z](https://www.0crat.com/u/jsoroka)

**Comment by 0crat** [comment]
> @0crat assign me ([here](https://github.com/llorllale/cactoos-matchers/issues/22#issuecomment-445462884))

@llorllale @llorllale[/z](https://www.0crat.com/u/llorllale) not enough funds available in the project, can't set budget of job [#22](https://github.com/llorllale/cactoos-matchers/issues/22), see [§21](http://www.zerocracy.com/policy.html#21); @llorllale[/z](https://www.0crat.com/u/llorllale) will get no money on completion; in order to fix that, add funds to the project and assign the job again

**Comment by llorllale** [comment]
@jsoroka fixed in f4dcb3253d8b1ab9c8c2abff9c2bd67f5d82458c, can we close this?

**Comment by 0crat** [comment]
Manual assignment of issues is discouraged, see [§19](http://www.zerocracy.com/policy.html#19): -5 point(s) just awarded to @llorllale[/z](https://www.0crat.com/u/llorllale)

**Comment by jsoroka** [comment]
LGTM
