### ISSUE TITLE
org.llorllale.cactoos.matchers.RunsInThreadsTest.matchNegative(RunsInThreadsTest.java:61)

### ISSUE THREAD

**Issue by dgroup** [llorllale/cactoos-matchers#55]
Observed in #48 
https://travis-ci.org/llorllale/cactoos-matchers/builds/465352255?utm_source=github_status&utm_medium=notification
```java
Tests run: 2, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 0.247 sec <<< FAILURE! - in org.llorllale.cactoos.matchers.RunsInThreadsTest
matchNegative(org.llorllale.cactoos.matchers.RunsInThreadsTest)  Time elapsed: 0.207 sec  <<< FAILURE!
java.lang.AssertionError: 
Can concurrently modify HashMap
Expected: <false>
     but: was <true>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.llorllale.cactoos.matchers.RunsInThreadsTest.matchNegative(RunsInThreadsTest.java:61)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.apache.maven.surefire.junitcore.pc.Scheduler$1.run(Scheduler.java:393)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
```

**Comment by 0crat** [comment]
@llorllale[/z](https://www.0crat.com/u/llorllale) please, pay attention to this issue

**Comment by llorllale** [comment]
@dgroup this is a dup of #51 (you were too slow... :) )

**Comment by 0crat** [comment]
Job `gh:llorllale/cactoos-matchers#55` is not assigned, can't get performer

**Comment by 0crat** [comment]
This job is not in scope
